.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH RAUG 8 "April 27, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
raug \- Run As User-Group
.SH SYNOPSIS
.B raug
.RI [ options ] " files" ...
.br
.B bar
.RI [ options ] " files" ...
.SH DESCRIPTION
This manual page documents briefly the
.B raug
command.
.PP
.B raug
is a simple utility that allows the superuser to run
commands as a different user and/or group. For example \fBraug\fP 
can be used to run some command as the user logging in using
the pam_exec PAM module.

.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.

.TP
.B \-u, \-\-user=USER
run COMMAND as USER  (precedes --user-envvar)

.TP
.B \-g, \-\-group=GROUP
run COMMAND as GROUP (precedes --group-envvar)

.TP
.B \-U, \-\-user\-envvar=ENVVAR
run COMMAND as user read from environment variable ENVVAR

.TP
.B \-G, \-\-group\-envvar=ENVVAR
run COMMAND as user read from environment variable ENVVAR

.TP
.B  \-\-verbose
print to stdout what is done

.TP
.B  \-\-help
Show summary of options.

.TP
.B  \-\-version
Show version of program.

.SH AUTHOR
raug was written by Heiko Noordhof <h.e.noordhof@rug.nl>.
